### ISSUE TITLE
大神请教一个问题

### ISSUE THREAD

**Issue by 26597925** [howl-anderson/WeatherBot_NLU#1]
"error": "bad value(s) in fds_to_keep"，我为什么运行后执行就报这个错误呀！

**Comment by howl-anderson** [comment]
@26597925 建议降级 scikit-learn。如果解决了问题欢迎回来关闭 issue, 如果没有解决问题，那么提请提供当前你的 scikit-learn 的版本等信息

**Comment by wenford** [comment]
我开始装19版本的没有成功，所以后面用了scikit-learn    0.20.1这个版本，谢谢！

**Comment by 26597925** [comment]
我用的当前版本是scikit-learn：0.20.1，我之所以用这个版本，是因为我安装19版本报错了，     ----------------------------------------
Command "/usr/local/opt/python/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-install-x2mp1whc/scikit-learn/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/tmp/pip-record-9pkzp149/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-install-x2mp1whc/scikit-learn/

**Comment by 26597925** [comment]
error: no member named 'exc_traceback' in '_ts'; did you mean 'curexc_traceback'?主要是这个错误日志。

**Comment by howl-anderson** [comment]
使用 Python 3.6 尝试一下。貌似 TF 还不支持 3.7，我从网上搜索，貌似 scikit-learn 对 Python 3.7 支持也不好。欢迎反馈！

**Comment by 26597925** [comment]
好的，多谢大神指点。

**Comment by 26597925** [comment]
安装3.6确实可以安装了，但是还是报错："error": "'SVC' object has no attribute '_impl'"

**Comment by howl-anderson** [comment]
参考这个，你的应该也是这个问题：https://github.com/RasaHQ/rasa_nlu/issues/1463

**Comment by 26597925** [comment]
好的，谢谢！
